### ISSUE TITLE
[PE-D][Tester D] `add` command prevents users from using valid emails

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-3/tp#223]
The `add` command allows for limited use of special characters in the email field. However, a valid email according to the internet standard allows for much more use of special characters such as '%' which is rejected by the system. A user who wants to use this legitimate email will find it extremely inconvenient.

![image.png](https://raw.githubusercontent.com/weiliann/ped/main/files/5614c10b-ced6-4af3-a5a7-d5c25b472c64.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: weiliann/ped#9

**Comment by Potatoad88** [comment]
Emails cannot have '%' and error message states what can be used for local-part
