### ISSUE TITLE
[PE-D][Tester D] inaccurate error message for `unpin`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F10-3/tp#238]
as a new user, i mistakenly typed 0, but instead of throwing invalid input, i get invalid command format which is misleading. since the format require is 'unpin index' which i have given

![image.png](https://raw.githubusercontent.com/weiliann/ped/main/files/ac7560e9-a36b-478c-89ff-35e6963c3f63.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: weiliann/ped#16

**Comment by Potatoad88** [comment]
functionality is working as expected so won't be changing the error message as it is not a bug
