### ISSUE TITLE
[PE-D][Tester E] Suggestion for sort command success message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F10-3/tp#260]
Success message when inputting `sorti 1 f/Price o/L` shows the following. 

It would be clearer to replace `L` with `ascending` order as users might not know what `L order` refers to. 

![image.png](https://raw.githubusercontent.com/xGladiate/ped/main/files/3daf66fd-29de-431b-a77e-7a28766f1161.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xGladiate/ped#10

**Comment by Potatoad88** [comment]
functionality works so can't change success message as it is not a bug
